# Generated by Django 4.1.6 on 2023-02-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountbook",
            name="memo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
